### ISSUE TITLE
About hardware

### ISSUE THREAD

**Issue by 7ASSEL** [prajwalsingh/EEGStyleGAN-ADA#10]
Thanks for your excellent work! Could you please tell me what GPU and VRAM do we need to train the model?

**Comment by prajwalsingh** [comment]
Hi @7ASSEL , thank you for reading our work.

We used Rtx Quadro 5000 (16GB) for training and inference of EEG features, and for training StyleGAN-ADA, we used Tesla V100 (32GB).

**Comment by 7ASSEL** [comment]
> Hi @7ASSEL , thank you for reading our work.
> 
> We used Rtx Quadro 5000 (16GB) for training and inference of EEG features, and for training StyleGAN-ADA, we used Tesla V100 (32GB).

Thanks a lot!
