### ISSUE TITLE
about cvpr40 dataset

### ISSUE THREAD

**Issue by HoshinoXxs** [prajwalsingh/EEGStyleGAN-ADA#11]
thanks for excellent work
when i run evluate.py in Triplet_LSTM/CVPR40, the model seems go wrong and unfitting

the model file is EEGStyleGAN-ADA-main/EEG2Feat/Triplet_LSTM/CVPR40/EXPERIMENT_29/bestckpt/eegfeat_all_0.9665178571428571.pth

the val files are: eeg_imagenet40_cvpr_2017/val

the result is as follow:
[Epoch: 8042, Test KMeans score Proj: 0.0802407221664995]
[0.02255639 0.04010025 0.01503759 0.02756892 0.03768844]
cv_scores mean:0.02859032002115842

looking forward to a reply

**Comment by prajwalsingh** [comment]
Hi @HoshinoXxs , thank you for reading the work.

I cloned the code and re-run it on my system without any changes, and it gives 96% for the test and 96.7% for val (evaluate.py) of what was proposed in the paper. 

I hope you are providing the correct dataset path (raw EEG, not 5_95 Hz). Kindly cross-check it. The only error I got was missing the directory; the rest of the results are accurate.

**Comment by HoshinoXxs** [comment]
> Hi @HoshinoXxs , thank you for reading the work.
> 
> I cloned the code and re-run it on my system without any changes, and it gives 96% for the test and 96.7% for val (evaluate.py) of what was proposed in the paper.
> 
> I hope you are providing the correct dataset path (raw EEG, not 5_95 Hz). Kindly cross-check it. The only error I got was missing the directory; the rest of the results are accurate.

thanks for reply

after using the raw dataset, it works
