### ISSUE TITLE
thoughtviz directory doesn't have eeg/image/data.pkl

### ISSUE THREAD

**Issue by x2x5** [prajwalsingh/EEGStyleGAN-ADA#13]
Thanks for sharing your great work on EEG2Image!

I tried to run your code and downloaded the dataset, thoughtviz.

but I can't find and don't understand what is `thoughtviz_path = 'b2i_data/eeg/image/data.pkl'`

After unzip the dataset, I can only see these files.

![image](https://github.com/prajwalsingh/EEGStyleGAN-ADA/assets/135324241/2a211768-147b-4905-8ca4-561b452847bb)

**Comment by prajwalsingh** [comment]
Hi @jaycee-tian, thank you for reading our work.

You can find that here [[link](https://iitgnacin-my.sharepoint.com/:u:/g/personal/19210048_iitgn_ac_in/Ea9s0JboxN1Ivr8NSuzcEOIBA_FnrGLSl7r461hDcxTbUg?e=n7e6cz)]. I have updated the same at dataset location.

**Comment by x2x5** [comment]
> Hi @jaycee-tian, thank you for reading our work.
> 
> You can find that here [[link](https://iitgnacin-my.sharepoint.com/:u:/g/personal/19210048_iitgn_ac_in/Ea9s0JboxN1Ivr8NSuzcEOIBA_FnrGLSl7r461hDcxTbUg?e=n7e6cz)]. I have updated the same at dataset location.

Oh!! so great!! Thank you so much for your excellent work and high quality code~
