### ISSUE TITLE
ThoughtViz and Object dataset

### ISSUE THREAD

**Issue by jontyharrison** [prajwalsingh/EEGStyleGAN-ADA#16]
Hi there, great paper!

I am trying to recreate the metric results on ThoughtViz EEG2Image but having issues with the data not being structured in the same way. I managed to produce the results on CVPR40.

In the link given in [EEGCVPR40 Dataset Availability · Issue #1 · prajwalsingh/EEGStyleGAN-ADA (github.com)](https://github.com/prajwalsingh/EEGStyleGAN-ADA/issues/1) the data is not structured how it is in [EEGStyleGAN-ADA/EEGStyleGAN-ADA_ThoughtViz/cmd_metricalc.txt at main · prajwalsingh/EEGStyleGAN-ADA (github.com)](https://github.com/prajwalsingh/EEGStyleGAN-ADA/blob/main/EEGStyleGAN-ADA_ThoughtViz/cmd_metricalc.txt) .

The code requires the image and EEG data to be linked but in that dataset it is not, I was wondering if there is a link to the data structured to match the .txt or a link to code to create that data structure.

Also in EEG2Feat for the Object dataset, the dataset in the link does not match what the code is expecting in https://github.com/prajwalsingh/EEGStyleGAN-ADA/blob/main/EEG2Feat/Triplet_LSTM/Object/config.py. Is the code to process the data available?

Many thanks!

**Comment by prajwalsingh** [comment]
Hi @jontyharrison , thank you for reading our work. 

For the Thoughtviz dataset, kindly check this issue [[link](https://github.com/prajwalsingh/EEG2Image/issues/11)] and for the Object dataset, we have uploaded the split of the data that we have used in our work [[Object Dataset Split](https://iitgnacin-my.sharepoint.com/:u:/g/personal/19210048_iitgn_ac_in/EU-p2_3-5HtHvCgc7jtb-ZYBaar86hmDW6uNTeCusWPfKA?e=HcHgdt)] (code I am not able to find that we use to create the split, might have missed it while taking the project backup).
