### ISSUE TITLE
Question: EEGCVPR40 Raw Dataset

### ISSUE THREAD

**Issue by gyuseok0917** [prajwalsingh/EEGStyleGAN-ADA#17]
hello. I am currently a student conducting research using the code from this github site. You posted a link to the repository of data used in your research, so I downloaded it and used it.
One question here is what frequency band the "EEGCVPR40 Raw" data has, other than the "EEGCVPR40 Filter (5-95 Hz)" data filtered to the 5-95 band.

![image](https://github.com/prajwalsingh/EEGStyleGAN-ADA/assets/147016361/69c46a5f-c8ae-44af-a28e-20cc0af59e44)

**Comment by gyuseok0917** [comment]
hello. I am currently a student conducting research using the code from this github site. You posted a link to the repository of data used in your research, so I downloaded it and used it.
One question here is what frequency band the "EEGCVPR40 Raw" data has, other than the "EEGCVPR40 Filter (5-95 Hz)" data filtered to the 5-95 band.

![image](https://github.com/prajwalsingh/EEGStyleGAN-ADA/assets/147016361/55cc8279-1a5e-417a-8ff0-25edf85b04ad)

**Comment by prajwalsingh** [comment]
HI @gyuseok0917 , we haven't checked the band of raw EEG data, we used normalization based on maximum frequency for feature extraction.
