### ISSUE TITLE
Question: EEG CVPR40 Dataset's Channel Names

### ISSUE THREAD

**Issue by gyuseok0917** [prajwalsingh/EEGStyleGAN-ADA#19]
[https://github.com/perceivelab/eeg_visual_classification/issues/4](https://github.com/perceivelab/eeg_visual_classification/issues/4)
I confirmed in the paper that the EEGCVPR40 Dataset you used was acquired using the same measurement method as EEGImageNet. The link above is the address of a question posted in the issue category of Github for the EEG-ImageNet Dataset. When you enter the link, the channel names are indicated and the order in which the 128 channels shown in the picture below are located. I'm also curious as to whether the CVPR40 Dataset has the same or different channel order as presented here, and whether microvolts are the same as EEGImageNet.
![image](https://github.com/prajwalsingh/EEGStyleGAN-ADA/assets/147016361/1790d557-4c15-4193-9f59-c5a3313d5c74)

**Comment by prajwalsingh** [comment]
> The link above is the address of a question posted in the issue category of Github for the EEG-I

Hi @gyuseok0917 , CVPR40 is actually the same dataset that is used in eeg_visual_classification. For the convenience, in our work we just name it so.
