### ISSUE TITLE
whats the functionality of EEGStyleGAN-ADA/Image2EEG directory?

### ISSUE THREAD

**Issue by nihilisticneuralnet** [prajwalsingh/EEGStyleGAN-ADA#21]
i am confused coz the code is very similar to EEGStyleGAN-ADA/Triplet_LSTM/. which dataset does it use?

**Comment by prajwalsingh** [comment]
@nihilisticneuralnet Hi, it maps unseen images to its equivalent EEG feature. It is something like zero-shot EEG feature generation. In paper, there is an experiment of image to image mapping which shows that, even if we have unseen image we can encode it into its equivalent EEG features and then pass it through the EEGStyleGAN for image generation.

**Comment by nihilisticneuralnet** [comment]
thanks for the reply
