### ISSUE TITLE
Question: about eeg preprocessing

### ISSUE THREAD

**Issue by gyuseok0917** [prajwalsingh/EEGStyleGAN-ADA#23]
Hello. I have a question regarding handling EEG data in this code. The author did not do any noise processing such as frequency filtering of EEG or artifact removal using ICA in EEGCVPR40 or Thoughtviz datasets, but most EEG to Image Generation inputs noisy EEG directly into the network without any preprocessing. Do you know anything about this?

**Comment by prajwalsingh** [comment]
Hi @gyuseok0917, if you see other EEG-related work like emotion classification, you will find that extensive noise pre-processing is applied, and so on. The EEGCVPR40 and ThoughtViz datasets for both filtering-based pre-processing are used while collecting the dataset, as mentioned in their respective papers.

Intuitively, while using deep learning-based techniques, we want to network to identify crucial EEG channels required for the task, i.e., determining the valuable information from noisy information without human intervention; we want the network to learn this identification. 

In our work, we applied a simple data normalization step, i.e., zero-centering the values; it gives the method a little boost.
