### ISSUE TITLE
Question: about pytorch version

### ISSUE THREAD

**Issue by gyuseok0917** [prajwalsingh/EEGStyleGAN-ADA#26]
Hello. I have a question about Pytorch version compatibility in relation to the use of the code. The markdown manual states that Pytorch 1.7.0 with CUDA 11.0 version is used when installing the library. My server environment uses Pytorch 1.13.0 with CUDA 11.6, and I would like to know if there is no problem in running the code without changing the version.

**Comment by prajwalsingh** [comment]
Hi @gyuseok0917, if you have the latest cuda install, there might be no issue. At that time, it had an older version, which is why there were some issues. The specific reason was that when I tried running the metric computation code, it was not working at that time.
