### ISSUE TITLE
Question: About the process of obtaining EEGCLIP's Top-k Accuracy

### ISSUE THREAD

**Issue by gyuseok0917** [prajwalsingh/EEGStyleGAN-ADA#27]
Hello. I have a question about the evaluation of EEGCLIP.
EEGCLIP learns to have high similarity between 1:1 pairs of EEG-Images, and when obtaining top-1, 3, and 5 accuracy,
is it measured by seeing whether the pairs are exactly matched or whether there are identical classes within k?
(Other papers utilizing the CLIP structure between EEG and images sometimes use the latter method,
so I would like to ask you about the exact evaluation method.)

**Comment by prajwalsingh** [comment]
Hi @gyuseok0917 , top-1 accuracy is equivalent to the accuracy that we measure in general. The reset Top-5 or Top-k checks whether they have a match in Top K predicted classes or not.
