### ISSUE TITLE
About the method of eeg feature input？

### ISSUE THREAD

**Issue by dzl20221020** [prajwalsingh/EEGStyleGAN-ADA#28]
I am honored to see such a good method. I read this paper carefully. The paper mentioned using a four-layer LSTM/CNN as a feature extraction network, and then inputting the 128-dimensional features into the generator of StyleGAN-ADA. I think this is a very good method. Then I read the source code carefully, but I found that in _**EEGStyleGAN-ADA_CVPR40/training/dataset.py**_, **_the EEG feature is returned as a con, and then in training_loop.py and loss.py, I saw that this con is actually passed into the discriminator as a conditional variable similar to stylegan2_**. I feel that this is inconsistent with the network structure in the paper. Can you explain?Or is there something wrong with my understanding? Could you please answer my question?

**Comment by prajwalsingh** [comment]
Hi @dzl20221020 , thank you for reading our work.

If you can observe the network architecture:

![image](https://github.com/user-attachments/assets/49d31b68-5ddc-4a67-8f71-b80fbf4f1c25)

An arrow is added to depict the same. This is done to train the discriminator also on conditional labels, which is part of "training conditional gans." You can watch [this](https://www.youtube.com/watch?v=6QG3t3jioUc) video for conditional gan explanation.

**Comment by dzl20221020** [comment]
OK, I think I understand. The line from the EEG feature to the generator in the network structure diagram misled me. Thank you for your answer.
