### ISSUE TITLE
Error in from cmd.txt script

### ISSUE THREAD

**Issue by A-Ayerh** [prajwalsingh/EEGStyleGAN-ADA#3]
Hello, I was wondering if someone could help me with solving an issue from the script from this txt file:

[EEGStyleGAN-ADA](https://github.com/prajwalsingh/EEGStyleGAN-ADA/tree/main)/[EEGStyleGAN-ADA_CVPR40](https://github.com/prajwalsingh/EEGStyleGAN-ADA/tree/main/EEGStyleGAN-ADA_CVPR40)
/cmd.txt script

The error produced while run:

```
Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: derivative for aten::grid_sampler_2d_backward is not implemented
```

How do I work through debugging this issue?
Thanks

**Comment by A-Ayerh** [comment]
Im currently using Pytorch 2.1.2 and CUDA 11.8

**Comment by prajwalsingh** [comment]
Hi @A-Ayerh, thank you for checking our work. Follow the instructions to use StyleGAN2-ADA:

# conda create -n to1.7 anaconda python=3.8
# conda activate to1.7
# pip install torch==1.7.0+cu110 torchvision==0.8.1+cu110 torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
# pip install opencv-python==4.5.4.58 opencv-contrib-python==4.5.4.58
# pip install natsort

**Comment by A-Ayerh** [comment]
Thank you so much! 
That helped fix the issue
