### ISSUE TITLE
EEGClip weights

### ISSUE THREAD

**Issue by ZechengLi19** [prajwalsingh/EEGStyleGAN-ADA#4]
Hi. Thanks for your wonderful work! I want to use the pre-trained EEGClip weights from your work. Could you share them with me? 

Thanks a lot~

**Comment by prajwalsingh** [comment]
Hi @ZechengLi19, thank you for reading our work. You can find EEGCLIP weights here [[link](https://iitgnacin-my.sharepoint.com/:u:/g/personal/19210048_iitgn_ac_in/Ec28u_yuWJVCmXNBjx6OldgBF0vtme6LXvzKP80V23uHKw?e=RB58yh)]. 

We have also updated the same in the Readme file.

**Comment by ZechengLi19** [comment]
Thanks for the pre-trained weight, this is very useful for me!

CLIP is a great piece of work, and so is EEGCLIP, which makes a lot of sense for the community!
