### ISSUE TITLE
Missing File 

### ISSUE THREAD

**Issue by A-Ayerh** [prajwalsingh/EEGStyleGAN-ADA#5]
Hello again,

I'm getting this error when running the image2eeg2image.py:

`FileNotFoundError: [Errno 2] No such file or directory: 'imageckpt/eegfeat_all_0.6875.pth'`

I couldn't find this file anywhere in the source code, do you have a link to the pth file by chance?

Thank You!

**Comment by prajwalsingh** [comment]
Hi @A-Ayerh, we have updated the link for imageckpt in the readme file. You can find the ckpt here, first create an imageckpt folder and put this pth file there [[link](https://iitgnacin-my.sharepoint.com/:u:/g/personal/19210048_iitgn_ac_in/EQuJKUdXz8lGn04O2KSwsAUBUdsL-rjj0FdDwNH1Z8V9jw?e=716Xuq)].

**Comment by A-Ayerh** [comment]
Sweet it worked, thank you!
