### ISSUE TITLE
How to run with my own dataset.

### ISSUE THREAD

**Issue by A-Ayerh** [prajwalsingh/EEGStyleGAN-ADA#6]
It's probably not so simple, but I was wondering how I would format my dataset to work with your model.
Let's say I have a set of EEG data and pictures that were presented during the experiment when the EEG data was collected.

Do you know how I could format my dataset to work with your model?
Can I structure it to be read like the CVPR40 dataset?

This is probably not enough information to work with, but could get pointed in the right direction for this?

Thank you!

**Comment by A-Ayerh** [comment]
Thanks @prajwalsingh!

One last thing, what is CVPR40 dataset format?

**Comment by prajwalsingh** [comment]
@A-Ayerh, this is the format Numpy file is arranged in:

[image, eeg, image_label, image_id, subject_number]

[H x W x 3, 128 x 440,  label, string, int32]

If you only have an image, label, and eeg, you can arrange it in the following way:

[image, eeg, label, None, None]

**Comment by A-Ayerh** [comment]
You are the man. 
I'll let you know how it goes  👍

**Comment by prajwalsingh** [comment]
@A-Ayerh, Do share the results of the experiments on different datasets. Looking forward to it.

**Comment by prajwalsingh** [comment]
@A-Ayerh, for image synthesis, I have shared the command for the same in the txt file.

python generate.py --network out/00001-EEGImageCVPR40-cond-mirror-cifar-batch64-bgcfnc/network-snapshot-005443.pkl --outdir generated_images/4 --seeds 0-10 --data=../dataset/eeg_imagenet40_cvpr_2017_raw/test/* 

Using the above, you can synthesize the image using the cvpr40 dataset, or the test can point to your own dataset.
