### ISSUE TITLE
EEGCLIP config file

### ISSUE THREAD

**Issue by zihang-xu** [prajwalsingh/EEGStyleGAN-ADA#7]
Hello~Thanks for your great work! I tried to reproduce the EEGCLIP with CVPR40 5-95hz and run the main.py, but could only get a KMeans score of about 0.04. It may be the problem with the config file. Could you please share this part? Or other guidance would be appreciated. : )

**Comment by prajwalsingh** [comment]
Hi @zihang-xu , thank you for reading our work.

Please refer to these issues for more information [ [link](https://github.com/prajwalsingh/EEGStyleGAN-ADA/issues/2#issuecomment-1891597052), [link](https://github.com/prajwalsingh/EEGStyleGAN-ADA/issues/4#issuecomment-1911751814) ]. 

If you still have any doubts, do let us know.

**Comment by zihang-xu** [comment]
Here are some of my processes for reproducing the paper. I downloaded CVPR40 5-95hz zip and ran main.py. I tried with the paper, but the result was still not satisfactory. I think I missed some details. 
Could you point me in the right direction, please? Thanks again!
![屏幕截图 2024-02-04 173359](https://github.com/prajwalsingh/EEGStyleGAN-ADA/assets/67997773/1a4bc5f0-305d-40df-8365-22cffe9ade54)
![屏幕截图 2024-02-04 175722](https://github.com/prajwalsingh/EEGStyleGAN-ADA/assets/67997773/938dea1b-5132-4e72-9d03-d63339a5c4e4)

**Comment by prajwalsingh** [comment]
Hi @zihang-xu , here are the few things that I observed in the training code at this line [[link](https://github.com/prajwalsingh/EEGStyleGAN-ADA/blob/4100dcdd0b65fd38b9804ae750a4da2943c092e8/EEGClip/main.py#L237)], we are not passing the config file configuration so network is using default initialised parameters that is:
<pre>in_channels=128, n_features=128, projection_dim=256, num_layers=1</pre>. 

Make sure that you have the correct extracted data of 5-95Hz, you can find the one that we have used [[link](https://iitgnacin-my.sharepoint.com/:u:/g/personal/19210048_iitgn_ac_in/ETX97Aw-USZd1HHU5mpIJmABPpl4fMCdEfkudJtuqRvNOw?e=3DFciF)], try running on this. 

Yo can also test the checkpoints that we have shared.

**Comment by zihang-xu** [comment]
Thank you very much! I will give them a try.

**Comment by prajwalsingh** [comment]
Hi @zihang-xu,

Did you run the code? Are there any updates regarding the results?

**Comment by zihang-xu** [comment]
Thank you very much for your concern and patience. I didn't follow up on this work continuously because of the holiday.
I see the researcher is following up on the work about "EEGClip" at this link [https://github.com/prajwalsingh/EEGStyleGAN-ADA/issues/9#issuecomment-1968347433](url). I encountered similar problems and [https://github.com/prajwalsingh/EEGStyleGAN-ADA/blob/main/EEGClip/topkrecall.py](url) doesn't print any metrics.
I will keep an eye on the latest updates. Thanks again!
![屏幕截图 2024-02-28 141126](https://github.com/prajwalsingh/EEGStyleGAN-ADA/assets/67997773/e21c0f28-d355-4a0c-ae6e-a21afdae071b)
![屏幕截图 2024-02-28 143818](https://github.com/prajwalsingh/EEGStyleGAN-ADA/assets/67997773/31578384-71a4-4672-8310-ad1583f74187)

**Comment by prajwalsingh** [comment]
Hi @zihang-xu, thank you for your reply.

We are looking into it and will keep posting the latest findings in this [ [thread](https://github.com/prajwalsingh/EEGStyleGAN-ADA/issues/9) ]. The problem arises due to messy code. We will clean it and update it on Git Hub.

**Comment by prajwalsingh** [comment]
Hi @zihang-xu , we have figured out the cause and explained it [here](https://github.com/prajwalsingh/EEGStyleGAN-ADA/issues/9#issuecomment-1969719968).

**Comment by zihang-xu** [comment]
Thank you for your explanation and patience. I will read and study the code carefully.
